### ISSUE TITLE
Need help to run turnserver

### ISSUE THREAD

**Issue by pjmun** [jitsi/turnserver#10]
Nice to meet you and your project.
I want to relay stream data with this turnserver.
Can i get advices with below two questions ?

I updated pom.xml(added universe.xml, updated jain-sdp version to 1.0-jitsi-1-SNAPSHOT)
also update TurnServer.java as below
--------------------------------code start----------------------------------------
 while (true) {
         Thread.sleep(20 \* 1000);
         if (server.isStarted()) {
                 //server.shutDown();
                 logger.info("Server is running.");
         }
 }
--------------------------------code end----------------------------------------

and executed this project in Eclipse as 
$ mvn clean package exec:java (with option : -Dexec.mainClass=org.jitsi.turnserver.stack.TurnServer)
1. turnserver uses too much cpu(278%), memory(1.36g) .
   Is this normal status ? or i builded and executed wrong ?
   --------------------------------linux top command----------------------------------------
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   19883 pjmun     20   0 8312700 1.362g  14860 S 278.0  7.0   0:56.45 java
2. Some errors and fails when a test client connects to turnserver.
   This test client connects well with coturn server which is different turn server.
   Do i need to update code or config file ? Do you have other test client to test turnserver ?

--------------------------------error message in turnserver----------------------------------------
WARNING: A net access point has gone useless:
java.lang.ArrayIndexOutOfBoundsException
    at java.net.SocketInputStream.read(SocketInputStream.java:162)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at org.ice4j.socket.DelegatingSocket.receiveFromInputStream(DelegatingSocket.java:76)
    at org.ice4j.socket.DelegatingSocket.receive(DelegatingSocket.java:632)
    at org.ice4j.socket.MultiplexingSocket.multiplexingXXXSocketSupportDoReceive(MultiplexingSocket.java:351)
    at org.ice4j.socket.MultiplexingSocket.access$000(MultiplexingSocket.java:34)
    at org.ice4j.socket.MultiplexingSocket$1.doReceive(MultiplexingSocket.java:78)
    at org.ice4j.socket.MultiplexingXXXSocketSupport.receive(MultiplexingXXXSocketSupport.java:724)
    at org.ice4j.socket.MultiplexingSocket.receive(MultiplexingSocket.java:408)
    at org.ice4j.socket.IceTcpSocketWrapper.receive(IceTcpSocketWrapper.java:146)
    at org.ice4j.stack.Connector.run(Connector.java:203)
    at java.lang.Thread.run(Thread.java:745)

Sep 13, 2016 9:47:34 AM org.ice4j.stack.NetAccessManager handleFatalError
WARNING: Removing connector:ice4j.Connector@10.177.174.54:3478/tcp status:  running
java.lang.ArrayIndexOutOfBoundsException
    at java.net.SocketInputStream.read(SocketInputStream.java:162)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at org.ice4j.socket.DelegatingSocket.receiveFromInputStream(DelegatingSocket.java:76)
    at org.ice4j.socket.DelegatingSocket.receive(DelegatingSocket.java:632)
    at org.ice4j.socket.MultiplexingSocket.multiplexingXXXSocketSupportDoReceive(MultiplexingSocket.java:351)
    at org.ice4j.socket.MultiplexingSocket.access$000(MultiplexingSocket.java:34)
    at org.ice4j.socket.MultiplexingSocket$1.doReceive(MultiplexingSocket.java:78)
    at org.ice4j.socket.MultiplexingXXXSocketSupport.receive(MultiplexingXXXSocketSupport.java:724)
    at org.ice4j.socket.MultiplexingSocket.receive(MultiplexingSocket.java:408)
    at org.ice4j.socket.IceTcpSocketWrapper.receive(IceTcpSocketWrapper.java:146)
    at org.ice4j.stack.Connector.run(Connector.java:203)
    at java.lang.Thread.run(Thread.java:745)

**Comment by ssdst** [comment]
i   have  same   problem .   i  try   to  solve  it   but   i  do  not  know   how  to  analysis  the  question  .   do  you  solve  it  and  how  to  solve  it?
